"""
LDT (Labordatenträger) parser — extracts lab results from simplified LDT files.

Uses the shared xDT parser for line-level parsing, then maps LDT-specific
Satzarten and Feldkennungen to typed dataclasses.

NOTE: This parses the simplified xDT-format LDT files generated by
scripts/generate_sample_ldt.py. For full LDT 3.2.19 compliance (nested
Obj_XXXX wrappers), extend this parser or use the official KBV test files
in data/samples/ldt/.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from klinika.standards.xdt import (
    get_field,
    get_fields,
    get_satzart,
    parse_records,
    read_xdt_file,
)

# LDT Satzarten
SA_HEADER = "8220"
SA_BEFUND = "8221"
SA_END = "8222"

# Field IDs for lab results
FK_PATIENT_ID = "3000"
FK_ORDER_NR = "8310"
FK_SAMPLE_DATE = "8410"
FK_SAMPLE_TIME = "8411"
FK_VALUE = "8420"
FK_UNIT = "8421"
FK_REF_LOW = "8422"
FK_REF_HIGH = "8423"
FK_FLAG = "8470"


@dataclass
class LabValue:
    test_code: str
    test_name: str
    value: str
    unit: str
    ref_low: str
    ref_high: str
    flag: str  # H=high, L=low, N=normal


@dataclass
class LabResult:
    patient_id: str
    order_nr: str
    sample_date: str
    sample_time: str
    values: list[LabValue] = field(default_factory=list)


@dataclass
class LDTData:
    results: list[LabResult] = field(default_factory=list)


def _parse_befund_record(record: list[tuple[str, str]]) -> LabResult:
    """Extract a LabResult from a SA 8221 record.

    Our simplified LDT format reuses field IDs:
    - First 8410/8411 = sample_date/sample_time (before any 8420)
    - Subsequent groups of 8410/8411/8420/8421/8422/8423/8470 = lab values

    Strategy: split fields into groups anchored by 8410. First group is
    the header (date/time), remaining groups each start with test_code.
    """
    patient_id = get_field(record, FK_PATIENT_ID) or ""
    order_nr = get_field(record, FK_ORDER_NR) or ""

    # Collect all fields excluding 8000 (Satzart)
    fields = [(fid, val) for fid, val in record if fid != "8000"]

    # Split into groups: each group starts with 8410
    groups: list[list[tuple[str, str]]] = []
    current_group: list[tuple[str, str]] = []
    for fid, val in fields:
        if fid == FK_SAMPLE_DATE:  # 8410
            if current_group:
                groups.append(current_group)
            current_group = [(fid, val)]
        else:
            current_group.append((fid, val))
    if current_group:
        groups.append(current_group)

    # First group before any 8420 = header (patient_id, order_nr, sample_date, sample_time)
    # Groups containing 8420 = lab values
    sample_date = ""
    sample_time = ""
    values: list[LabValue] = []

    for group in groups:
        group_dict = {fid: val for fid, val in group}

        if FK_VALUE in group_dict:
            # This is a lab value group
            values.append(LabValue(
                test_code=group_dict.get(FK_SAMPLE_DATE, ""),   # 8410 = test code in value groups
                test_name=group_dict.get("8411", ""),            # 8411 = test name
                value=group_dict.get(FK_VALUE, ""),              # 8420
                unit=group_dict.get(FK_UNIT, ""),                # 8421
                ref_low=group_dict.get(FK_REF_LOW, ""),          # 8422
                ref_high=group_dict.get(FK_REF_HIGH, ""),        # 8423
                flag=group_dict.get(FK_FLAG, ""),                # 8470
            ))
        else:
            # Header group — extract date/time
            if FK_SAMPLE_DATE in group_dict and not sample_date:
                sample_date = group_dict[FK_SAMPLE_DATE]
            if "8411" in group_dict and not sample_time:
                sample_time = group_dict["8411"]

    return LabResult(
        patient_id=patient_id,
        order_nr=order_nr,
        sample_date=sample_date,
        sample_time=sample_time,
        values=values,
    )


def parse_ldt(path: str | Path) -> LDTData:
    """Parse a simplified LDT file into structured lab data."""
    content = read_xdt_file(path)
    records = parse_records(content)
    data = LDTData()

    for record in records:
        satzart = get_satzart(record)
        if satzart == SA_BEFUND:
            data.results.append(_parse_befund_record(record))

    return data
